# Generated by Django 3.0.3 on 2020-03-06 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('rec_user_level', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by',
                                                 to=settings.AUTH_USER_MODEL)),
                ('participants',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
