# Generated by Django 3.0.3 on 2020-03-16 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arrangements', '0001_squashed_0005_auto_20200315_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnitNight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knit_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by1',
                                   to=settings.AUTH_USER_MODEL)),
                ('participants',
                 models.ManyToManyField(blank=True, related_name='participants1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
