# Generated by Django 3.0.3 on 2020-03-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('arrangements', '0002_knitnight'),
    ]

    operations = [
        migrations.AddField(
            model_name='knitnight',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
