# Generated by Django 3.0.3 on 2020-03-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('personal_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_feed_post',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
