# Generated by Django 3.0.3 on 2020-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_User',
            field=models.BooleanField(default=False),
        ),
    ]
