# Generated by Django 3.0.3 on 2020-03-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_completed_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='completed_challenges',
            field=models.IntegerField(default=0),
        ),
    ]
