# Generated by Django 3.0.3 on 2020-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200323_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='completed_challenges',
            field=models.IntegerField(null=True),
        ),
    ]
